### ISSUE TITLE
Invalid specifications version throws an error

### ISSUE THREAD

**Issue by depryf** [imsweb/naaccr-xml#256]
A dictionary had value "1" for the specification and that crashed the library instead of reporting a "normal" error.

```java
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.imsweb.naaccrxml.SpecificationVersion.compareSpecifications(SpecificationVersion.java:43) ~[naaccr-xml-10.1.jar:10.1]
	at com.imsweb.naaccrxml.NaaccrXmlDictionaryUtils.readDictionary(NaaccrXmlDictionaryUtils.java:372) ~[naaccr-xml-10.1.jar:10.1]
	at com.imsweb.naaccrxml.NaaccrXmlDictionaryUtils.readDictionary(NaaccrXmlDictionaryUtils.java:341) ~[naaccr-xml-10.1.jar:10.1]
```

**Comment by depryf** [comment]
This is fixed.
